services:
  backend:
    build: .
    image: roothub:latest
    container_name: roothub-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
      # - redis
    ports:
      - 8000:8000

  db:
    image: postgres:alpine3.20
    container_name: roothub-postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025

  # celery_worker:
  #   build: .
  #   image: roothub-backend-celery
  #   command: celery -A roothub worker -l info
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
  #     - backend

  # celery_beat:
  #   build: .
  #   image: roothub-backend-celery-beat
  #   command: celery -A roothub beat -l info --scheduler django_celery_beat.schedulers.DatabaseScheduler
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
  #     - backend

  # redis:
  #   image: redis:alpine

volumes:
  postgres_data:

