# Generated by Django 5.1.2 on 2024-12-24 06:01

import django.db.models.deletion
import utils.util_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(db_index=True, default=utils.util_functions.generate_uuid, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('duration', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], max_length=2)),
                ('level', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], max_length=2)),
                ('instructor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.instructor')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='authentication.program')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.CharField(db_index=True, default=utils.util_functions.generate_uuid, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_end_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='course.coursesession')),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course.studentcourse')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentcourse',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course'),
        ),
        migrations.AddConstraint(
            model_name='studentcoursesession',
            constraint=models.UniqueConstraint(fields=('student_course', 'course_session'), name='unique_student_course_session'),
        ),
    ]
