# Generated by Django 5.1.2 on 2024-10-10 09:16

import django.db.models.deletion
import utils.util_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(db_index=True, default=utils.util_functions.generate_uuid, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('monthly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('duration', models.CharField(choices=[('1', '1 month'), ('2', '2 months'), ('3', '3 months'), ('4', '4 months')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.CharField(db_index=True, default=utils.util_functions.generate_uuid, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('estimated_end_date', models.DateField()),
                ('session_info', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('end_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='course.course')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='course_session', to='authentication.student', verbose_name='students')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseTutor',
            fields=[
                ('id', models.CharField(db_index=True, default=utils.util_functions.generate_uuid, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.coursesession')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.instructor')),
            ],
            options={
                'unique_together': {('instructor', 'course_session')},
            },
        ),
        migrations.AddField(
            model_name='coursesession',
            name='instructors',
            field=models.ManyToManyField(related_name='course_sessions', through='course.CourseTutor', to='authentication.instructor'),
        ),
        migrations.CreateModel(
            name='CourseSessionPayment',
            fields=[
                ('id', models.CharField(db_index=True, default=utils.util_functions.generate_uuid, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('course_session', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='course.coursesession')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.instructor')),
            ],
            options={
                'unique_together': {('instructor', 'course_session')},
            },
        ),
    ]
