# Generated by Django 5.1.2 on 2025-01-04 14:16

import django.utils.timezone
import utils.util_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='id',
            field=models.CharField(db_index=True, default=utils.util_functions.generate_uuid, max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
