# Generated by Django 5.1.2 on 2024-10-10 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesession',
            name='instructors',
        ),
        migrations.DeleteModel(
            name='CourseTutor',
        ),
        migrations.AddField(
            model_name='coursesession',
            name='instructors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_session', to='authentication.instructor'),
        ),
    ]
