# Generated by Django 5.1.2 on 2024-10-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_coursesession_instructors_delete_coursetutor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesession',
            name='students',
        ),
    ]
