# Generated by Django 5.1.2 on 2025-01-05 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_student_session_and_more'),
        ('course', '0002_studentcourse_created_at_studentcourse_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.instructor'),
        ),
    ]
