# Generated by Django 5.1.2 on 2024-10-10 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_student_course_session'),
        ('course', '0003_remove_coursesession_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesession',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='instructors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_session', to='authentication.instructor'),
        ),
    ]
