# Generated by Django 5.1.2 on 2025-01-09 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_student_user'),
        ('course', '0003_alter_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='course.course'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authentication.student'),
        ),
        migrations.AlterField(
            model_name='studentcoursesession',
            name='course_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_sessions', to='course.coursesession'),
        ),
        migrations.AlterField(
            model_name='studentcoursesession',
            name='student_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sessions', to='course.studentcourse'),
        ),
    ]
