# Generated by Django 5.1.2 on 2025-01-10 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_studentcourse_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='coursesession',
            options={'ordering': ['-created_at']},
        ),
    ]
