# Generated by Django 5.1.2 on 2024-12-27 18:36

import utils.util_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.CharField(db_index=True, default=utils.util_functions.generate_uuid, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('message', models.TextField()),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('receiver_group', models.CharField(choices=[('ALL', 'All'), ('TRAINER', 'Trainer'), ('TRAINEE', 'Trainee')], default='ALL', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
