# Generated by Django 5.1.2 on 2024-12-24 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', through='course.StudentCourse', to='course.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='students', to='authentication.program'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
