# Generated by Django 5.1.2 on 2024-12-25 09:32

import django.db.models.deletion
import utils.util_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorSkill',
            fields=[
                ('id', models.CharField(db_index=True, default=utils.util_functions.generate_uuid, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.instructor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.CharField(db_index=True, default=utils.util_functions.generate_uuid, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('plan', models.CharField(choices=[('MONTHLY', 'Monthly'), ('FULL', 'Full'), ('PART', 'Part')], max_length=20)),
                ('payment_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
