# Generated by Django 5.1.2 on 2024-12-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_instructorskill_studentpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpayment',
            name='plan',
        ),
    ]
