# Generated by Django 5.1.2 on 2024-12-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_studentpayment_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='skills',
        ),
    ]
