# Generated by Django 5.1.2 on 2024-12-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_instructor_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instructorskill',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_plan',
            field=models.CharField(choices=[('FULL', 'FULL'), ('PART', 'PART'), ('NOT PAID', 'NOT PAID')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='next_of_kin_contact',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='next_of_kin_relationship',
            field=models.CharField(choices=[('SISTER', 'sister'), ('BROTHER', 'brother'), ('FATHER', 'father'), ('MOTHER', 'mother'), ('SON', 'son'), ('DAUGHTER', 'daughter'), ('FRIEND', 'friend'), ('PARTNER', 'partner'), ('COLLEAGUE', 'colleague')], max_length=40),
        ),
    ]
