# Generated by Django 5.1.2 on 2024-12-29 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_instructor_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorskill',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='authentication.instructor'),
        ),
    ]
