# Generated by Django 5.1.2 on 2025-01-04 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_instructorskill_instructor'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='students', to='course.coursesession'),
        ),
        migrations.AlterUniqueTogether(
            name='instructorskill',
            unique_together={('instructor', 'is_primary')},
        ),
    ]
