# Generated by Django 5.1.2 on 2025-01-09 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_student_session_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instructorskill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='instructor',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='authentication.instructorskill'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='instructorskill',
            name='instructor',
        ),
    ]
