# Generated by Django 5.1.2 on 2025-01-10 03:54

import django.db.models.deletion
import utils.util_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.CharField(db_index=True, default=utils.util_functions.generate_uuid, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='instructorskill',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='studentpayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='instructorskill',
            name='name',
        ),
        migrations.AddField(
            model_name='instructorskill',
            name='instructor_id',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='authentication.instructor'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='skills',
        ),
        migrations.AddField(
            model_name='instructorskill',
            name='Skill_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.skill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='skills',
            field=models.ManyToManyField(through='authentication.InstructorSkill', to='authentication.skill'),
        ),
    ]
