# Generated by Django 5.1.2 on 2025-01-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_skill_alter_instructor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorskill',
            options={},
        ),
        migrations.AddConstraint(
            model_name='instructorskill',
            constraint=models.UniqueConstraint(fields=('instructor_id', 'is_primary'), name='single_instructor_primary_skill'),
        ),
    ]
