# Generated by Django 5.1.2 on 2025-01-10 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_instructorskill_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorskill',
            old_name='Skill_id',
            new_name='skill_id',
        ),
    ]
