# Generated by Django 5.1.2 on 2025-01-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_rename_skill_id_instructorskill_skill_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='instructorskill',
            constraint=models.UniqueConstraint(fields=('instructor_id', 'skill_id'), name='unique_instructor_skill'),
        ),
    ]
