# Generated by Django 5.1.2 on 2025-01-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_instructorskill_unique_instructor_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='curriculum',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
